- name: Demo on variables1
  hosts: all
  vars:
    URL: example.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL = {{URL}} # or "URL = {{ URL }}"


- name: Demo on variables2
  hosts: all
  vars:
    URL: example.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Demo on variables3
  hosts: all
  vars:
    URL: example.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: '{{ URL }}'

- name: Demo on variables4
  hosts: all
  vars:
    URL: "example.com"
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}