- name: Demo on variables1
  hosts: all
  vars:
    URL: example.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL = {{ URL }} # or "URL = {{ URL }}" and spaces inside peranthasis not needed


- name: Demo on variables2
  hosts: all
  vars:
    URL: example.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Demo on variables3
  hosts: all
  vars:
    URL: example.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: '{{ URL }}'

- name: Demo on variables4
  hosts: all
  vars:
    URL: "example.com"
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Demo on file variables
  hosts: all
  vars_files:
    - sample-variable-file
  tasks:
    - ansible.builtin.debug:
        msg: "{{URL}}"

- name: Task level variable
  hosts: all
  tasks:
    - name: print url from task
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: task.example.com

- name: Variable from Inventory
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{ URL }}

