- name: Demo on variables1
  hosts: all
  vars:
    URL: example.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: "URL = {{ URL }}"


- name: Demo on variables2
  hosts: all
  vars:
    URL: example.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: "{{ URL }}"