- name: Demo on pulling aws secrets and parameters
  hosts: localhost
  tasks:
    - name: pull secrets
      debug: msg="{{ lookup('amazon.aws.aws_secret', 'roboshop/all-secrets', region='us-east-1') }}"
    - name: pull parameter
      debug: msg="{{ lookup('aws_ssm', 'roboshop.test', region='us-east-1' ) }}"