- name: Create Parameters
  hosts: localhost
  tasks:
    - name: Update a Parameter
      community.aws.aws_ssm_parameter_store:
        name: "roboshop-parameter"
        string_type: "String"
        value: "roboshop.com"
        overwrite_value: "always"





