- name: create line playbook
  hosts: localhost
  tasks:
    -name: Add a line to a file if the file does not exist, without passing regexp
    ansible.builtin.lineinfile:
    path: /tmp/testfile
    line: 192.168.1.99 foo.lab.net foo
    create: yes # If specified, the file will be created if it does not already exist.