- name: create line playbook
  hosts: localhost
  tasks:
    - name: Add a line to a file if the file does not exist, without passing regexp
      ansible.builtin.lineinfile:
        path: /tmp/testfile
        line: added new line
        create: yes # If specified, the file will be created if it does not already exist.

    - name: search a line and replace
      ansible.builtin.lineinfile:
        path: /tmp/testfile
        regexp: uid
        line: uid = 1001