- name : demo on list loops
  hosts : localhost
  tasks :
    - name : print loops
      ansible.builtin.debug:
        msg : Fruit Name = {{item}}
      loop:
        - apple
        - banana
        - orange

- name : demo on  map loops
  hosts : localhost
  tasks :
    - name : print loops
      ansible.builtin.debug:
        msg : Fruit Name = {{item.name}} , quantity = {{item.quantity}}
      loop:
       - { name: "apple", quantity: 100 }
       - { name: "banana", quantity: 200 }


- name: coming out of a loop
  hosts: localhost
  tasks:
    - name: break the loop
      ansible.builtin.debug:
        msg: Number = {{item}}
      loop:
        - 1
        - 2
        - 3
        - 4
      loop_control:
        break_when:  item >= 3