- name : demo on loops
  hosts : localhost
  tasks :
    - name : print loops
      ansible.builtin.debug:
        msg : Fruit Name = {{item}}
      loop:
        - apple
        - banana
        - orange
