- name: run shell command
  ansible.builtin.shell: uptime
  register: out

- name: print uptime output
  ansible.builtin.debug:
    msg: output = {{out.stdout}}

- name: Print url
  ansible.builtin.debug:
    msg: "{{URL}}"

#By default, Ansible looks for the sample.yml file within the tasks/ directory of a role. This sample.yml serves as the default entry point for the role.