- name: run shell command
  ansible.builtin.shell: uptime
  register: out

- name: print uptime output
  ansible.builtin.debug:
    msg: output = {{out.stdout}}

- name: Print url
  ansible.builtin.debug:
    msg: "{{URL}}"